### ISSUE TITLE
ExpressCompletePurchaseResponse getTransactionReference() error

### ISSUE THREAD

**Issue by dmaksimov** [thephpleague/omnipay-paypal#146] opened 2016-10-06 16:49 UTC
After completing the Express Checkout purchase, doing $response->getTransactionReference() on the response returns the token instead of the transaction id.

**Comment by lukeholder** [comment] 2016-11-07 04:44
We are getting the same error when trying to refund a transaction.

Getting error "The Transaction Id Is Not Valid" back from paypal when trying to refund a transaction.

Was something changes in 2.6.1 @barryvdh ?

**Comment by delatbabel** [comment] 2016-11-07 06:08
Is this on the $response from the purchase() call or from the completePurchase() call?  My experience is with the REST gateway that you can only use the transaction reference that you get from the result of the completePurchase() call to do refunds.

**Comment by lukeholder** [comment] 2016-11-07 06:43
I am talking about the transaction reference returned on the complete purchase response.

The response to `getTransactionReference()` on the inital `purchase` request returns:

`EC-81393565CA631930L`

I create a pending transaction on my system with the reference set to the above and then redirect the user to paypal.

Paypal then calls my complete payment action and I update my transaction based on the response from calling `completePurchase()` - it returns successful but the call to `getTransactionReference()` on that response also returns:

`EC-81393565CA631930L`

When I go to refund the transaction, the reference above is used, and the response error is `The Transaction Id Is Not Valid` code: 10004.

**Comment by delatbabel** [comment] 2016-11-07 06:50
Hrm, OK that sounds like a bug.

I have checked this on the REST gateway and it works fine for me.  The transactionReference from the purchase() call and the transactionReference from the completePurchase() call are different.  The one from the completePurchase() call is the correct one to use.

I have no idea whether this has changed as a result of changes at PayPal or changes in the code, but looking at recent changes in the ExpressCompletePurchaseResponse class there are no changes in the last year or so that could have caused this.

The next debugging step is to dump the entire of the data() from a call to completePurchase() and see whether anything has changed in the response from PayPal.  Unfortunately I don't have a PayPal Express test setup, only a PayPal REST setup, and as I said with the REST classes it's working fine.  Hopefully this gives you an idea of where to look though.

**Comment by lukeholder** [comment] 2016-11-07 06:54
this is the dump from the complete purchase response data:

```
{
   "TOKEN":"EC-68M49059EP120553V",
   "SUCCESSPAGEREDIRECTREQUESTED":"false",
   "TIMESTAMP":"2016-11-07T06:50:58Z",
   "CORRELATIONID":"405e39d1805b1",
   "ACK":"Success",
   "VERSION":"119.0",
   "BUILD":"26755900",
   "INSURANCEOPTIONSELECTED":"false",
   "SHIPPINGOPTIONISDEFAULT":"false",
   "PAYMENTINFO_0_TRANSACTIONID":"9KM46426KY375415S",
   "PAYMENTINFO_0_TRANSACTIONTYPE":"cart",
   "PAYMENTINFO_0_PAYMENTTYPE":"instant",
   "PAYMENTINFO_0_ORDERTIME":"2016-11-07T06:50:57Z",
   "PAYMENTINFO_0_AMT":"26.53",
   "PAYMENTINFO_0_TAXAMT":"0.00",
   "PAYMENTINFO_0_CURRENCYCODE":"GBP",
   "PAYMENTINFO_0_PAYMENTSTATUS":"Pending",
   "PAYMENTINFO_0_PENDINGREASON":"multicurrency",
   "PAYMENTINFO_0_REASONCODE":"None",
   "PAYMENTINFO_0_PROTECTIONELIGIBILITY":"Eligible",
   "PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE":"ItemNotReceivedEligible,UnauthorizedPaymentEligible",
   "PAYMENTINFO_0_SELLERPAYPALACCOUNTID":"lukemh-facilitator@gmail.com",
   "PAYMENTINFO_0_SECUREMERCHANTACCOUNTID":"9XF486N48W4TQ",
   "PAYMENTINFO_0_ERRORCODE":"0",
   "PAYMENTINFO_0_ACK":"Success"
}
```

**Comment by lukeholder** [comment] 2016-11-07 06:56
Assume it's the `PAYMENTINFO_0_TRANSACTIONID` ?

**Comment by delatbabel** [comment] 2016-11-07 06:57
Yup, it looks like this contains your correct transactionId:

    "PAYMENTINFO_0_TRANSACTIONID":"9KM46426KY375415S",

I don't believe that we've ever needed to dig that out.  Previously we've just used the ID.  So this is obviously a recent change at PayPal and requires a patch from us.  PR requested please, as I said I don't have a PayPal express test account.  The code change required should be reasonably obvious but make it fall back to ID if that PAYMENTINFO_0_TRANSACTIONID is not there.

**Comment by delatbabel** [comment] 2016-11-07 07:01
I note that the REST gateway has always needed to do this, so it's possibly PayPal bringing their Express gateway into line with their REST gateway.  I wonder if Pro has suddenly developed the same problem.

**Comment by lukeholder** [comment] 2016-11-07 07:03
Just used the 

```
"PAYMENTINFO_0_TRANSACTIONID":"9KM46426KY375415S",
```

And the transaction successfully refunded.

**Comment by lukeholder** [comment] 2016-11-07 07:32
Thinking I will go with the below in ExpressCompletePurchaseResponse @delatbabel ?

```
    public function getTransactionReference()
    {
        if ($this->isSuccessful() && isset($this->data['PAYMENTINFO_0_TRANSACTIONID']))
        {
            return $this->data['PAYMENTINFO_0_TRANSACTIONID'];
        }

        return parent::getTransactionReference();
    }
```

tested and working. We only want to update the reference on success, since a redirect response on completePurchase still wants to keep the TOKEN.

**Comment by delatbabel** [comment] 2016-11-08 03:40
That looks like it should work.

**Comment by delatbabel** [comment] 2016-11-08 03:42
Also please add a note to the Quirks section of the gateway docblocks that the transaction reference obtained from the purchase() call can't be used to refund a purchase, and that the transaction reference from the completePurchase() call is the one that's actually needed.

**Comment by lukeholder** [comment] 2016-11-08 11:27
@barryvdh good catch, I had not looked at the Response.php to see that it has the `PAYMENTINFO_0_TRANSACTIONID` in the list.

I would guess that only the purchase() & authorize() response will want the `TOKEN` as the `transactionReference`.

I am not a fan of the Response baseclass having an array of fallbacks to provide the `transactionReference`. I would rather see us create additional subclasses of each response type that know what data they are looking for and want to deal with.

TBH I would need to read the paypal doc (yikes) to know whether putting TOKEN at the end of  the array would even work in every gateway response situation - I would be uneasy doing that would a bunch of testing.

**Comment by barryvdh** [comment] 2016-11-08 11:30
That would indeed be better. I'm not sure why they used an array to 'guess' the field to use, but the correct thing would be to use just the correct one. (Unfortunately I don't use paypal)

**Comment by emilv** [comment] 2016-11-29 15:47
@lukeholder Do you need help to move the PR forward? If I am correct we are stuck on the fact that we should stop guessing the transactionReference in the superclass, but instead explicitly declare the right one in each subclass, correct?

This is a huge bug since a lot of users of Omnipay-paypal probably just logs the transactionReference number. The guessing behavior is already there in the released version of the library and didn't cause issues before. Paying off technical debt is always nice but should not delay important bugfixes if the bugfix itself doesn't introduce more debt. So here is my suggestion:

1. Let's merge the PR. It solves the problem and doesn't introduce more technical debt. There is nothing wrong or objectionable about the PR.
2. Leave the issue open while we pay off the technical debt, alternatively open a new issue.

**Comment by lukeholder** [comment] 2016-11-30 01:25
@delatbabel @barryvdh Any objection to just merging https://github.com/thephpleague/omnipay-paypal/pull/151 ? 

I agree it fixes the issue for now for Express Refunds, we can then open a new issue to think about removing the `transactionReference` array guessing code in the parent class.

cc @emilv

**Comment by delatbabel** [comment] 2016-12-10 04:50
> @delatbabel @barryvdh Any objection to just merging #151 ?

My only objection to merging #151 was that you said not to merge it.  Check the comment history.

**Comment by lukeholder** [comment] 2016-12-10 05:17
Happy to have it merged. That comment was when the original merge request was made a month ago. The comment in this thread is 10 days asking if we should proceed with merge.

**Comment by microstudi** [comment] 2016-12-22 12:34
I don't understand why you guys don't merge this. I had to manually edit composer in order fetch the code from the pull request to fix this very annoying bug.

**Comment by barryvdh** [comment] 2016-12-22 12:34
Because it says 'Still discussing in #146, do not merge yet.'

**Comment by barryvdh** [comment] 2016-12-22 12:35
I merged it, can you guys test it and let me know it's all good? Then I could tag a release

**Closed** 2016-12-22 12:35 UTC

**Comment by microstudi** [comment] 2016-12-22 12:43
I see, In my experience (about 3 weeks now) with this fix in produccion, no problems so far. Transaction code is ok now.

**Comment by cfreear** [comment] 2017-02-08 16:21
Root cause of this issue was 08806a0
