### ISSUE TITLE
No error returned.

### ISSUE THREAD

**Issue by njdubois** [thephpleague/omnipay-paypal#165] opened 2017-06-30 21:35 UTC
We work with Non-profits, want to allow the org to bring their own payment gateways so I have written an app that well determine the gateway, and if possible use omnipay to donate to that org.  We don't have a paypal pro account and are stuck waiting for paypal so we are trying to use a clients api keys.

I submit the payment and get "" back from paypal.  I'd have to say this is a pretty big deal, can we please get some sort of error reporting?  Or am I missing something?  Shouldn't getMessage say something other than "" ??

**Comment by delatbabel** [comment] 2017-07-01 03:30
OK firstly a few points:

* This is not a forum for support for omnipay or the omnipay-paypal gateway. This is a bug tracker.  The correct forum for omnipay or omnipay-paypal issues is StackOverflow, with questions tagged as "omnipay".  I am active there daily and happy to answer support questions, but the issue that you have raised is not a demonstrated bug.
* There is not enough information in "I submit the payment and get "" back from paypal".  It would help to show what your code looks like so we have a chance of figuring out what the issue is.

I will close this, please re-raise on StackOverflow.

**Closed by delatbabel** 2017-07-01 03:30 UTC
