### ISSUE TITLE
getTransactionId() undefined method

### ISSUE THREAD

**Issue by adaniello** [thephpleague/omnipay-paypal#99] opened 2015-11-30 22:45 UTC
Hi,
i'm testing PayPal Express. In doc (https://github.com/thephpleague/omnipay readme) about "Successful Response" i read:

"...
The following methods are always available:
...
$response->getTransactionId(); // the reference set by the originating website if available.
...."

but if i try to use getTransactionId() method, i get the following:

Fatal error: Call to undefined method Omnipay\PayPal\Message\ExpressAuthorizeResponse::getTransactionId()

For PayPal Express this method not exists.

Thanks,
Achille

**Comment by leith** [comment] 2015-12-01 00:19
ExpressAuthorizeResponse is just for the redirect to PayPal - no transaction has taken place yet, so there's no transaction ID.

**Comment by adaniello** [comment] 2015-12-01 08:23
But transactionId is a "custom" "reference set by the originating website, if available". So i think that this should/could be useful in every circumstances.
Maybe also in authors mind is the same, if in doc they write "following methods are always available".

**Comment by adaniello** [comment] 2015-12-01 09:20
Just now i noted that github info about responses (https://github.com/thephpleague/omnipay readme) is different from thephpleague site (http://omnipay.thephpleague.com/api/responses/): in this second there isn't any reference to $response->getTransactionId().

What's the latest "official"?

**Comment by judgej** [comment] 2015-12-01 11:16
I think it will depend on whether the transaction ID is available in the response. If you passed it into the request message that generated the response, then you should have that ID there if you need it. If the remote gateway sends it back in the response (more usual with notify callbacks) then it should be in the response.

However, it is not always going to be available or even appropriate in a response message, so isn't built into the core response message.

In short, sometimes it's there and sometimes it's not, depending entirely on gateway and the type of message (server-to-server, callback, etc.)

@adaniello I see that one of those links states that `getTransactionId()` will return the ID *if available* and the other link misses out that method completely. The truth lies somewhere in the middle - notify responses sometimes return the transactionId, direct (server-to-server) responses tend not to. So sometimes that method is available and sometimes it is not, because it is not in context.

**Comment by barryvdh** [comment] 2015-12-01 11:20
It's not in the interface, so it's not required; https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Message/ResponseInterface.php
So you can't rely on it. But I guess it would be easier to make it return `null` instead of giving an error, when not available.

**Comment by judgej** [comment] 2015-12-01 11:34
Are you suggesting putting it into the abstract response with a default `null` return, or moving to magic methods - `__get()` - so that ANY unknown field will return a null?

**Comment by barryvdh** [comment] 2015-12-01 11:51
Hmm, I see now that t's already there; https://github.com/thephpleague/omnipay-common/blob/2.4.0/src/Omnipay/Common/Message/AbstractResponse.php#L150-L158
Added by https://github.com/thephpleague/omnipay-common/pull/41

@adaniello What version of `omnipay-common` are you on?

**Comment by adaniello** [comment] 2015-12-01 12:02
@barryvdh i'm working with v 2.3.4

This is a good point because a transactionId getter/setter methods could be very useful  in every context.

**Comment by barryvdh** [comment] 2015-12-01 12:30
So can you run composer update? Or `composer require omnipay/common:"^2.4.0"`?

**Comment by adaniello** [comment] 2015-12-01 14:27
Yes! Done composer update but get "Nothing to install or update". If i try to require common 2.4.0 i get the following error:

Problem 1
    - omnipay/omnipay 2.3.2 requires omnipay/common ~2.3.0 -> no matching package found.
    - omnipay/omnipay 2.3.2 requires omnipay/common ~2.3.0 -> no matching package found.
    - omnipay/omnipay 2.3.2 requires omnipay/common ~2.3.0 -> no matching package found.
    - Installation request for omnipay/omnipay 2.3.2 -> satisfiable by omnipay/omnipay[2.3.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

**Comment by barryvdh** [comment] 2015-12-01 16:06
Loosened constraints in https://github.com/thephpleague/omnipay/commit/baab44f8266965ab68a199a8117043b4392ec60a
Should be good with `@dev` version for omnipay, or wait until it's tagged.

**Comment by adaniello** [comment] 2015-12-01 16:51
@barryvdh Also with --dev i get the same error.
Thanks

**Comment by delatbabel** [comment] 2016-03-25 10:47
Confirmed that this is working for me now with the latest tagged release.

**Closed by delatbabel** 2016-03-25 10:47 UTC
